services:

  backend:
    container_name: frugality_backend
    build:
      context: .
      dockerfile: backend_dockerfile
      args:
      - devcontainercli=true
    env_file:
      - path: ./prod.env
        required: true
    ports:
      - 8080:80
    depends_on:
      - database
    volumes:
      - type: bind
        source: ./backend
        target: /home/Frugality/backend

    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 60s

  database:
    container_name: frugality_db
    image: postgres:16.0-alpine3.18
    env_file:
    - path: ./prod.env
      required: true
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgres/data

    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  database:
    driver: local