version: "3.8"
services:


  backend:
    build:
      context: .
      args:
      - devcontainercli=true
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_PORT=5432
    ports:
      - 8080:80
    depends_on:
      - database
    volumes:
      - type: bind
        source: .
        target: /home/Frugality/app


  database:
    image: postgres:16.0-alpine3.18
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_NAME=${POSTGRES_NAME}
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgres/data
    restart: always


volumes:
  database:
    driver: local