query GetProductByName($StoreID: ID!, $query: String, $limit: Int, $slugs: String) {
    store(id: $StoreID) {
        name
        id
        brand
        products(
            limit: $limit
            includeAgeLimitedByAlcohol: true
            searchProvider: loop54
            queryString: $query
            slug: $slugs
        ) {
            items {
                name
                ean
                price
                basicQuantityUnit
                comparisonPrice
                comparisonUnit
                brandName
                slug
                hierarchyPath {
                    id
                    name
                    slug
                }
            }
        }
    }
}